import os

env = SConscript('../godot_cpp/SConstruct')
env.Append(CPPPATH=['src'])
dest_dir = '../../src/bin/geocr/'

num_jobs = ARGUMENTS.get('jobs', 4)
platform = ARGUMENTS.get('platform', 'windows')

if not os.path.exists(dest_dir):
    os.makedirs(dest_dir)

src = Glob('src/*.cpp')
print("Source files: ", src)
libpath = os.path.join(dest_dir, 'libgeocr' + env['suffix'] + env['SHLIBSUFFIX'])
sharedlib = env.SharedLibrary(libpath, src)

Default(sharedlib)