import os
import platform as os_platform

env = SConscript('../godot_cpp/SConstruct')
env.Append(CPPPATH=['src'])
# dest_dir = '../../src/bin/geocr/'

num_jobs = ARGUMENTS.get('jobs', 4)
platform = ARGUMENTS.get('platform', 'windows')

if not os.path.exists(dest_dir):
    os.makedirs(dest_dir, exist_ok=True)

if platform == 'windows':


src = Glob('src/*.cpp')
libpath = os.path.join('libgeocr' + env['suffix'] + env['SHLIBSUFFIX'])
sharedlib = env.SharedLibrary(libpath, src)

Default(sharedlib)